import React from 'react';
import { motion } from 'framer-motion';
import { Globe, RefreshCw, Zap, Users } from 'lucide-react';

const FeatureCard = ({ icon: Icon, title, desc }) => (
    <motion.div
        whileHover={{ scale: 1.02 }}
        className="card-base p-8 relative overflow-hidden group h-full"
    >
        {/* Frame Animation - Simplified */}
        <div className="absolute inset-0 rounded-2xl border-2 border-transparent group-hover:border-ubBlue transition-colors duration-300"></div>

        <div className="relative z-10 flex flex-col items-start text-left">
            <div className="p-4 bg-ubOffWhite rounded-xl mb-6 text-ubBlue group-hover:bg-ubBlue group-hover:text-white transition-colors border border-ubBorder">
                <Icon size={32} strokeWidth={1.5} />
            </div>
            <h3 className="text-2xl font-bold mb-4 text-ubBlack">{title}</h3>
            <p className="text-body">{desc}</p>
        </div>
    </motion.div>
);

export default function About() {
    return (
        <section id="about" className="py-24 px-4 bg-white relative overflow-hidden">
            {/* Very Subtle Background Decor */}
            <div className="absolute top-0 right-0 w-1/3 h-full bg-gradient-to-l from-ubOffWhite to-transparent pointer-events-none"></div>

            <div className="max-w-7xl mx-auto relative z-10">
                <div className="text-center mb-20">
                    <h2 className="section-heading">
                        The Protocol
                    </h2>
                    <div className="h-2 w-24 bg-ubBlue mx-auto rounded-full"></div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <FeatureCard
                        icon={Globe}
                        title="Ecosystem"
                        desc="The UBI Protocol aims to reward UBI holders by building income-generating platforms, and developers will also be supported, with the aim of encouraging diversification of projects within the Protocol."
                    />
                    <FeatureCard
                        icon={RefreshCw}
                        title="Sustainability"
                        desc="When a revenue-generating platform launched, UBI holders get more $USDC revenue, which supports the growth of a larger community. Subsequently, more platforms are launched using the protocol revenues generated, and the UBI community grows steadily."
                    />
                    <FeatureCard
                        icon={Zap}
                        title="Utility"
                        desc="$UBI is a utility token used by all ecosystem participants to receive a share of the $USDC profits generated by the revenue-generating platforms developed by the UBI Protocol."
                    />
                    <FeatureCard
                        icon={Users}
                        title="Community"
                        desc="Holders govern the direction of future developments, ensuring the protocol evolves to serve the collective interest of the ecosystem."
                    />
                </div>
            </div>
        </section>
    );
}
