import React from 'react';
import { motion } from 'framer-motion';
import { Globe, RefreshCw, Zap, Users } from 'lucide-react';

const FeatureCard = ({ icon: Icon, title, desc }) => (
    <motion.div
        whileHover={{ scale: 1.02 }}
        className="card-base p-8 relative overflow-hidden group h-full"
    >
        {/* Frame Animation - Simplified */}
        <div className="absolute inset-0 rounded-2xl border-2 border-transparent group-hover:border-ubBlue transition-colors duration-300"></div>

        <div className="relative z-10 flex flex-col items-start text-left">
            <div className="p-4 bg-ubOffWhite rounded-xl mb-6 text-ubBlue group-hover:bg-ubBlue group-hover:text-white transition-colors border border-ubBorder">
                <Icon size={32} strokeWidth={1.5} />
            </div>
            <h3 className="text-2xl font-bold mb-4 text-ubBlack">{title}</h3>
            <p className="text-body">{desc}</p>
        </div>
    </motion.div>
);

export default function About() {
    return (
        <section id="about" className="py-24 px-4 bg-white relative overflow-hidden">
            {/* Very Subtle Background Decor */}
            <div className="absolute top-0 right-0 w-1/3 h-full bg-gradient-to-l from-ubOffWhite to-transparent pointer-events-none"></div>

            <div className="max-w-7xl mx-auto relative z-10">
                <div className="text-center mb-20">
                    <h2 className="section-heading">
                        The Protocol
                    </h2>
                    <div className="h-2 w-24 bg-ubBlue mx-auto rounded-full"></div>
                </div>

                <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
                    <FeatureCard
                        icon={Globe}
                        title="Ecosystem"
                        desc="UBI Protocol builds a diversified ecosystem of income-generating platforms, designed to reward UBI holders with real, continuous USDC revenue. Developers are empowered to launch new projects within the Protocol, expanding the ecosystem and increasing the long-term value captured by early holders."
                    />
                    <FeatureCard
                        icon={RefreshCw}
                        title="Sustainability"
                        desc="Every time a revenue-generating platform goes live, UBI holders instantly gain access to more USDC revenue-fueling a compounding cycle of growth. Some of the revenues are then used to launch even more platforms, creating a self-sustaining expansion loop where the community and the Protocol grow together."
                    />
                    <FeatureCard
                        icon={Zap}
                        title="Utility"
                        desc="$UBI is the core utility token of the ecosystem, granting every holder a direct share of all USDC profits generated by UBI Protocol's revenue-generating platforms. Holding UBI means owning exposure to both token appreciation and real protocol revenue, a dual-benefit rarely seen in Web3."
                    />
                    <FeatureCard
                        icon={Users}
                        title="Community"
                        desc="UBI holders guide the direction of all future developments, ensuring the protocol evolves to maximize collective value. This is a community where ownership equals influence those who hold UBI shape the future of the ecosystem and share in its growing rewards."
                    />
                </div>
            </div>
        </section>
    );
}
