import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Plus, Minus } from 'lucide-react';

const faqData = [
    {
        question: "What is the UBI Protocol?",
        answer: "UBI Protocol is a revenue-sharing blockchain ecosystem where holders of the $UBI receive USDC distributions generated by multiple income-producing platforms."
    },
    {
        question: "How do $UBI holders earn USDC?",
        answer: "Each platform launched within the UBI ecosystem produces revenue. A portion of these revenues is accumulated and distributed directly to UBI holders, creating a recurring USDC income stream."
    },
    {
        question: "Why should I join the crowdfunding phase?",
        answer: "Crowdfunding participants receive access at the earliest—and most advantageous—allocation stage. Once the allocation closes or the price moves to the next tier, the cost of entering the ecosystem increases significantly."
    },
    {
        question: "When will the platforms launch?",
        answer: "Major UBI platforms such as the USDC Giveaway Platform, DeFi Layer, and Social App are scheduled for phased launches alongside or shortly after $UBI exchange listings, increasing demand and revenue potential for holders."
    },
    {
        question: "How will $UBI listings affect price and scarcity?",
        answer: "Listings typically increase visibility and demand. As new users enter the ecosystem, allocation becomes more competitive, and token scarcity may amplify price pressure—making early entry strategically valuable."
    }
];

const FAQItem = ({ question, answer }) => {
    const [isOpen, setIsOpen] = useState(false);

    return (
        <div className="border border-ubBorder rounded-xl overflow-hidden bg-white mb-4">
            <button
                onClick={() => setIsOpen(!isOpen)}
                className="w-full flex items-center justify-between p-6 text-left hover:bg-ubOffWhite transition-colors"
            >
                <span className="text-lg font-bold text-ubBlack">{question}</span>
                {isOpen ? <Minus className="text-ubBlue" /> : <Plus className="text-ubBlue" />}
            </button>
            <AnimatePresence>
                {isOpen && (
                    <motion.div
                        initial={{ height: 0, opacity: 0 }}
                        animate={{ height: "auto", opacity: 1 }}
                        exit={{ height: 0, opacity: 0 }}
                        transition={{ duration: 0.3 }}
                    >
                        <div className="p-6 pt-0 text-ubGray leading-relaxed border-t border-ubBorder/50">
                            {answer}
                        </div>
                    </motion.div>
                )}
            </AnimatePresence>
        </div>
    );
};

export default function FAQ() {
    return (
        <section id="faq" className="py-24 bg-white">
            <div className="max-w-4xl mx-auto px-4">
                <div className="text-center mb-16">
                    <h2 className="section-heading">FAQ</h2>
                    <p className="text-ubGray mt-4 text-lg">Frequently Asked Questions</p>
                </div>
                <div>
                    {faqData.map((item, index) => (
                        <FAQItem key={index} {...item} />
                    ))}
                </div>
            </div>
        </section>
    );
}
